// src/scripts/kukuData.js
// 九九のデータ（1の段〜9の段） + フル読み上げ・音声読み上げ調整データ

export const KUKU_DATA = {
  1: [
    { q: "1 × 1 =", a: 1, read: "いん いち が", fullRead: "いんいちがいち" },
    { q: "1 × 2 =", a: 2, read: "いん に が", fullRead: "いんにがに" },
    { q: "1 × 3 =", a: 3, read: "いん さん が", fullRead: "いんさんがさん" },
    { q: "1 × 4 =", a: 4, read: "いん し が", fullRead: "いんしがし" },
    { q: "1 × 5 =", a: 5, read: "いん ご が", fullRead: "いんごがご" },
    { q: "1 × 6 =", a: 6, read: "いん ろく が", fullRead: "いんろくがろく" },
    { q: "1 × 7 =", a: 7, read: "いん しち が", fullRead: "いんしちがしち" },
    { q: "1 × 8 =", a: 8, read: "いん はち が", fullRead: "いんはちがはち" },
    { q: "1 × 9 =", a: 9, read: "いん く が", fullRead: "いんくがく" },
  ],
  2: [
    { q: "2 × 1 =", a: 2, read: "に いち が", fullRead: "にいちがに" },
    { q: "2 × 2 =", a: 4, read: "に にん が", fullRead: "ににんがし" },
    { q: "2 × 3 =", a: 6, read: "に さん が", fullRead: "にさんがろく" },
    { q: "2 × 4 =", a: 8, read: "に し が", fullRead: "にしがはち" },
    { q: "2 × 5 =", a: 10, read: "に ご", fullRead: "にごじゅう" },
    { q: "2 × 6 =", a: 12, read: "に ろく", fullRead: "にろくじゅうに" },
    { q: "2 × 7 =", a: 14, read: "に しち", fullRead: "にしちじゅうし" },
    { q: "2 × 8 =", a: 16, read: "に はち", fullRead: "にはちじゅうろく" },
    { q: "2 × 9 =", a: 18, read: "に く", fullRead: "にくじゅうはち" },
  ],
  3: [
    { q: "3 × 1 =", a: 3, read: "さん いち が", fullRead: "さんいちがさん" },
    { q: "3 × 2 =", a: 6, read: "さん に が", fullRead: "さんにがろく" },
    { q: "3 × 3 =", a: 9, read: "さざん が", fullRead: "さざんがきゅう" },
    { q: "3 × 4 =", a: 12, read: "さん し", fullRead: "さんしじゅうに" },
    { q: "3 × 5 =", a: 15, read: "さん ご", fullRead: "さんごじゅうご" },
    { q: "3 × 6 =", a: 18, read: "さぶ ろく", fullRead: "さぶろくじゅうはち" },
    { q: "3 × 7 =", a: 21, read: "さん しち", fullRead: "さんしちにじゅういち" },
    { q: "3 × 8 =", a: 24, read: "さん ぱ", fullRead: "さんぱにじゅうし" },
    { q: "3 × 9 =", a: 27, read: "さん く", fullRead: "さんくにじゅうしち" },
  ],
  4: [
    { q: "4 × 1 =", a: 4, read: "し いち が", fullRead: "しいちがし" },
    { q: "4 × 2 =", a: 8, read: "し に が", fullRead: "しにがはち" },
    { q: "4 × 3 =", a: 12, read: "し さん", fullRead: "しさんじゅうに" },
    { q: "4 × 4 =", a: 16, read: "し し", fullRead: "ししじゅうろく" },
    { q: "4 × 5 =", a: 20, read: "し ご", fullRead: "しごにじゅう" },
    { q: "4 × 6 =", a: 24, read: "し ろく", fullRead: "しろくにじゅうし" },
    { q: "4 × 7 =", a: 28, read: "し しち", fullRead: "ししちにじゅうはち" },
    { q: "4 × 8 =", a: 32, read: "し は", ttsRead: "し ハ", fullRead: "しはさんじゅうに", ttsFullRead: "しハさんじゅうに" },
    { q: "4 × 9 =", a: 36, read: "し く", fullRead: "しくさんじゅうろく" },
  ],
  5: [
    { q: "5 × 1 =", a: 5, read: "ご いち が", fullRead: "ごいちがご" },
    { q: "5 × 2 =", a: 10, read: "ご に", fullRead: "ごにじゅう" },
    { q: "5 × 3 =", a: 15, read: "ご さん", fullRead: "ごさんじゅうご" },
    { q: "5 × 4 =", a: 20, read: "ご し", fullRead: "ごしにじゅう" },
    { q: "5 × 5 =", a: 25, read: "ご ご", fullRead: "ごごにじゅうご" },
    { q: "5 × 6 =", a: 30, read: "ご ろく", fullRead: "ごろくさんじゅう" },
    { q: "5 × 7 =", a: 35, read: "ご しち", fullRead: "ごしちさんじゅうご" },
    { q: "5 × 8 =", a: 40, read: "ご は", ttsRead: "ご ハ", fullRead: "ごはしじゅう", ttsFullRead: "ごハしじゅう" },
    { q: "5 × 9 =", a: 45, read: "ごっ く", fullRead: "ごっくしじゅうご" },
  ],
  6: [
    { q: "6 × 1 =", a: 6, read: "ろく いち が", fullRead: "ろくいちがろく" },
    { q: "6 × 2 =", a: 12, read: "ろく に", fullRead: "ろくにじゅうに" },
    { q: "6 × 3 =", a: 18, read: "ろく さん", fullRead: "ろくさんじゅうはち" },
    { q: "6 × 4 =", a: 24, read: "ろく し", fullRead: "ろくしにじゅうし" },
    { q: "6 × 5 =", a: 30, read: "ろく ご", fullRead: "ろくごさんじゅう" },
    { q: "6 × 6 =", a: 36, read: "ろく ろく", fullRead: "ろくろくさんじゅうろく" },
    { q: "6 × 7 =", a: 42, read: "ろく しち", fullRead: "ろくしちしじゅうに" },
    { q: "6 × 8 =", a: 48, read: "ろく は", ttsRead: "ろく ハ", fullRead: "ろくはしじゅうはち", ttsFullRead: "ろくハしじゅうはち" },
    { q: "6 × 9 =", a: 54, read: "ろっ く", fullRead: "ろっくごじゅうし" },
  ],
  7: [
    { q: "7 × 1 =", a: 7, read: "しち いち が", fullRead: "しちいちがしち" },
    { q: "7 × 2 =", a: 14, read: "しち に", fullRead: "しちにじゅうし" },
    { q: "7 × 3 =", a: 21, read: "しち さん", fullRead: "しちさんにじゅういち" },
    { q: "7 × 4 =", a: 28, read: "しち し", fullRead: "しちしにじゅうはち" },
    { q: "7 × 5 =", a: 35, read: "しち ご", fullRead: "しちごさんじゅうご" },
    { q: "7 × 6 =", a: 42, read: "しち ろく", fullRead: "しちろくしじゅうに" },
    { q: "7 × 7 =", a: 49, read: "しち しち", fullRead: "しちしちしじゅうきゅう" },
    { q: "7 × 8 =", a: 56, read: "しち は", ttsRead: "しち ハ", fullRead: "しちはごじゅうろく", ttsFullRead: "しちハごじゅうろく" },
    { q: "7 × 9 =", a: 63, read: "しち く", fullRead: "しちくろくじゅうさん" },
  ],
  8: [
    { q: "8 × 1 =", a: 8, read: "はち いち が", fullRead: "はちいちがはち" },
    { q: "8 × 2 =", a: 16, read: "はち に", fullRead: "はちにじゅうろく" },
    { q: "8 × 3 =", a: 24, read: "はち さん", fullRead: "はちさんにじゅうし" },
    { q: "8 × 4 =", a: 32, read: "はち し", fullRead: "はちしさんじゅうに" },
    { q: "8 × 5 =", a: 40, read: "はち ご", fullRead: "はちごしじゅう" },
    { q: "8 × 6 =", a: 48, read: "はち ろく", fullRead: "はちろくしじゅうはち" },
    { q: "8 × 7 =", a: 56, read: "はち しち", fullRead: "はちしちごじゅうろく" },
    { q: "8 × 8 =", a: 64, read: "はっ ぱ", fullRead: "はっぱろくじゅうし" },
    { q: "8 × 9 =", a: 72, read: "はっ く", fullRead: "はっくしちじゅうに" },
  ],
  9: [
    { q: "9 × 1 =", a: 9, read: "く いち が", fullRead: "くいちがく" },
    { q: "9 × 2 =", a: 18, read: "く に", fullRead: "くにじゅうはち" },
    { q: "9 × 3 =", a: 27, read: "く さん", fullRead: "くさんにじゅうしち" },
    { q: "9 × 4 =", a: 36, read: "く し", fullRead: "くしさんじゅうろく" },
    { q: "9 × 5 =", a: 45, read: "く ご", fullRead: "くごしじゅうご" },
    { q: "9 × 6 =", a: 54, read: "く ろく", fullRead: "くろくごじゅうし" },
    { q: "9 × 7 =", a: 63, read: "く しち", fullRead: "くしちろくじゅうさん" },
    { q: "9 × 8 =", a: 72, read: "く は", ttsRead: "く ハ", fullRead: "くはしちじゅうに", ttsFullRead: "くハしちじゅうに" },
    { q: "9 × 9 =", a: 81, read: "く く", fullRead: "くくはちじゅういち" },
  ],
};